include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/rust/frb_generated.dart
    - lib/src/rust/frb_generated.io.dart
    - lib/src/rust/frb_generated.web.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
