// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Optionally initializes the engine with a custom path.
///
/// If not called, the engine auto-initializes on first data operation
/// using a platform-appropriate default path.
Future<void> torexInitialize({String? path}) =>
    RustLib.instance.api.crateApiTorexInitialize(path: path);

/// Checks if the runtime is currently initialized.
Future<bool> torexIsInitialized() =>
    RustLib.instance.api.crateApiTorexIsInitialized();

/// Gracefully shuts down the runtime.
///
/// Not required — resources are cleaned up automatically on process exit.
/// Useful for explicit shutdown in testing or controlled environments.
Future<void> torexShutdown() => RustLib.instance.api.crateApiTorexShutdown();

/// Returns the current storage path (if initialized).
Future<String?> torexCurrentPath() =>
    RustLib.instance.api.crateApiTorexCurrentPath();

/// Legacy alias: opens the engine at the given path.
/// Kept for compatibility with generated FFI bridge code.
Future<void> torexOpen({required String path}) =>
    RustLib.instance.api.crateApiTorexOpen(path: path);

/// Legacy alias: closes the engine.
/// Kept for compatibility with generated FFI bridge code.
Future<void> torexClose() => RustLib.instance.api.crateApiTorexClose();

/// Stores a key-value pair in the specified collection.
/// Auto-initializes the runtime on first call.
Future<void> torexPut({
  required String collection,
  required List<int> key,
  required List<int> value,
}) => RustLib.instance.api.crateApiTorexPut(
  collection: collection,
  key: key,
  value: value,
);

/// Retrieves a value by key from the specified collection.
/// Auto-initializes the runtime on first call.
Future<Uint8List?> torexGet({
  required String collection,
  required List<int> key,
}) => RustLib.instance.api.crateApiTorexGet(collection: collection, key: key);

/// Deletes a key from the specified collection.
/// Auto-initializes the runtime on first call.
Future<void> torexDelete({
  required String collection,
  required List<int> key,
}) =>
    RustLib.instance.api.crateApiTorexDelete(collection: collection, key: key);

/// Checks if a key exists in the specified collection.
/// Auto-initializes the runtime on first call.
Future<bool> torexExists({
  required String collection,
  required List<int> key,
}) =>
    RustLib.instance.api.crateApiTorexExists(collection: collection, key: key);

/// Flushes the memtable to disk for the specified collection.
Future<void> torexFlush({required String collection}) =>
    RustLib.instance.api.crateApiTorexFlush(collection: collection);

/// Returns the number of entries in the memtable.
Future<BigInt> torexMemtableCount({required String collection}) =>
    RustLib.instance.api.crateApiTorexMemtableCount(collection: collection);

/// Returns the number of segments.
Future<BigInt> torexSegmentCount({required String collection}) =>
    RustLib.instance.api.crateApiTorexSegmentCount(collection: collection);

/// Lists all open collection names.
Future<List<String>> torexListCollections() =>
    RustLib.instance.api.crateApiTorexListCollections();

/// Stores a string key-value pair (convenience).
Future<void> torexPutString({
  required String collection,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiTorexPutString(
  collection: collection,
  key: key,
  value: value,
);

/// Gets a string value by string key (convenience).
Future<String?> torexGetString({
  required String collection,
  required String key,
}) => RustLib.instance.api.crateApiTorexGetString(
  collection: collection,
  key: key,
);

/// Batch puts multiple key-value pairs with a single WAL fsync.
/// Far more efficient than calling torex_put in a loop.
Future<void> torexBatchPut({
  required String collection,
  required List<(Uint8List, Uint8List)> entries,
}) => RustLib.instance.api.crateApiTorexBatchPut(
  collection: collection,
  entries: entries,
);

/// Returns the engine version.
Future<String> torexVersion() => RustLib.instance.api.crateApiTorexVersion();

/// Scans all entries in a collection with optional prefix filter and limit.
Future<List<TorexEntry>> torexScan({
  required String collection,
  Uint8List? prefix,
  Uint8List? startKey,
  Uint8List? endKey,
  BigInt? limit,
  BigInt? offset,
  required bool reverse,
}) => RustLib.instance.api.crateApiTorexScan(
  collection: collection,
  prefix: prefix,
  startKey: startKey,
  endKey: endKey,
  limit: limit,
  offset: offset,
  reverse: reverse,
);

/// Scans entries with string keys/values.
Future<List<(String, String)>> torexScanStrings({
  required String collection,
  String? prefix,
  String? startKey,
  String? endKey,
  BigInt? limit,
  BigInt? offset,
  required bool reverse,
}) => RustLib.instance.api.crateApiTorexScanStrings(
  collection: collection,
  prefix: prefix,
  startKey: startKey,
  endKey: endKey,
  limit: limit,
  offset: offset,
  reverse: reverse,
);

/// Returns all keys in a collection.
Future<List<Uint8List>> torexKeys({required String collection}) =>
    RustLib.instance.api.crateApiTorexKeys(collection: collection);

/// Returns the approximate count of entries in a collection.
Future<BigInt> torexCount({required String collection}) =>
    RustLib.instance.api.crateApiTorexCount(collection: collection);

/// Deletes all entries in a collection (drops and recreates).
Future<void> torexClearCollection({required String collection}) =>
    RustLib.instance.api.crateApiTorexClearCollection(collection: collection);

/// Batch deletes multiple keys with a single WAL fsync.
/// Far more efficient than calling torex_delete in a loop.
Future<void> torexBatchDelete({
  required String collection,
  required List<Uint8List> keys,
}) => RustLib.instance.api.crateApiTorexBatchDelete(
  collection: collection,
  keys: keys,
);

/// Subscribes to change events for a collection.
/// Returns a subscription ID used for polling and unsubscribing.
Future<BigInt> torexWatchCollection({required String collection}) =>
    RustLib.instance.api.crateApiTorexWatchCollection(collection: collection);

/// Subscribes to change events for keys with a prefix in a collection.
Future<BigInt> torexWatchPrefix({
  required String collection,
  required List<int> prefix,
}) => RustLib.instance.api.crateApiTorexWatchPrefix(
  collection: collection,
  prefix: prefix,
);

/// Subscribes to ALL change events.
Future<BigInt> torexWatchGlobal() =>
    RustLib.instance.api.crateApiTorexWatchGlobal();

/// Polls for pending watch events since last call.
/// Returns up to `max_events` events. Returns empty vec if no events pending.
Future<List<TorexWatchEvent>> torexWatchPoll({
  required BigInt subscriptionId,
  required int maxEvents,
}) => RustLib.instance.api.crateApiTorexWatchPoll(
  subscriptionId: subscriptionId,
  maxEvents: maxEvents,
);

/// Unsubscribes from watch events.
Future<void> torexWatchUnsubscribe({required BigInt subscriptionId}) => RustLib
    .instance
    .api
    .crateApiTorexWatchUnsubscribe(subscriptionId: subscriptionId);

/// A serializable query result entry.
class TorexEntry {
  final Uint8List key;
  final Uint8List value;

  const TorexEntry({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorexEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// A change event from the watcher.
class TorexWatchEvent {
  /// Collection name.
  final String collection;

  /// Key that changed.
  final Uint8List key;

  /// Change type: 0=Put, 1=Delete, 2=Clear.
  final int changeType;

  const TorexWatchEvent({
    required this.collection,
    required this.key,
    required this.changeType,
  });

  @override
  int get hashCode => collection.hashCode ^ key.hashCode ^ changeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorexWatchEvent &&
          runtimeType == other.runtimeType &&
          collection == other.collection &&
          key == other.key &&
          changeType == other.changeType;
}
