// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1966122795;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'torex_local_store',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiTorexBatchDelete({
    required String collection,
    required List<Uint8List> keys,
  });

  Future<void> crateApiTorexBatchPut({
    required String collection,
    required List<(Uint8List, Uint8List)> entries,
  });

  Future<void> crateApiTorexClearCollection({required String collection});

  Future<void> crateApiTorexClose();

  Future<BigInt> crateApiTorexCount({required String collection});

  Future<String?> crateApiTorexCurrentPath();

  Future<void> crateApiTorexDelete({
    required String collection,
    required List<int> key,
  });

  Future<bool> crateApiTorexExists({
    required String collection,
    required List<int> key,
  });

  Future<void> crateApiTorexFlush({required String collection});

  Future<Uint8List?> crateApiTorexGet({
    required String collection,
    required List<int> key,
  });

  Future<String?> crateApiTorexGetString({
    required String collection,
    required String key,
  });

  Future<void> crateApiTorexInitialize({String? path});

  Future<bool> crateApiTorexIsInitialized();

  Future<List<Uint8List>> crateApiTorexKeys({required String collection});

  Future<List<String>> crateApiTorexListCollections();

  Future<BigInt> crateApiTorexMemtableCount({required String collection});

  Future<void> crateApiTorexOpen({required String path});

  Future<void> crateApiTorexPut({
    required String collection,
    required List<int> key,
    required List<int> value,
  });

  Future<void> crateApiTorexPutString({
    required String collection,
    required String key,
    required String value,
  });

  Future<List<TorexEntry>> crateApiTorexScan({
    required String collection,
    Uint8List? prefix,
    Uint8List? startKey,
    Uint8List? endKey,
    BigInt? limit,
    BigInt? offset,
    required bool reverse,
  });

  Future<List<(String, String)>> crateApiTorexScanStrings({
    required String collection,
    String? prefix,
    String? startKey,
    String? endKey,
    BigInt? limit,
    BigInt? offset,
    required bool reverse,
  });

  Future<BigInt> crateApiTorexSegmentCount({required String collection});

  Future<void> crateApiTorexShutdown();

  Future<String> crateApiTorexVersion();

  Future<BigInt> crateApiTorexWatchCollection({required String collection});

  Future<BigInt> crateApiTorexWatchGlobal();

  Future<List<TorexWatchEvent>> crateApiTorexWatchPoll({
    required BigInt subscriptionId,
    required int maxEvents,
  });

  Future<BigInt> crateApiTorexWatchPrefix({
    required String collection,
    required List<int> prefix,
  });

  Future<void> crateApiTorexWatchUnsubscribe({required BigInt subscriptionId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiTorexBatchDelete({
    required String collection,
    required List<Uint8List> keys,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_list_prim_u_8_strict(keys, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexBatchDeleteConstMeta,
        argValues: [collection, keys],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexBatchDeleteConstMeta => const TaskConstMeta(
    debugName: "torex_batch_delete",
    argNames: ["collection", "keys"],
  );

  @override
  Future<void> crateApiTorexBatchPut({
    required String collection,
    required List<(Uint8List, Uint8List)> entries,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
            entries,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexBatchPutConstMeta,
        argValues: [collection, entries],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexBatchPutConstMeta => const TaskConstMeta(
    debugName: "torex_batch_put",
    argNames: ["collection", "entries"],
  );

  @override
  Future<void> crateApiTorexClearCollection({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexClearCollectionConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexClearCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "torex_clear_collection",
        argNames: ["collection"],
      );

  @override
  Future<void> crateApiTorexClose() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexCloseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexCloseConstMeta =>
      const TaskConstMeta(debugName: "torex_close", argNames: []);

  @override
  Future<BigInt> crateApiTorexCount({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexCountConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexCountConstMeta =>
      const TaskConstMeta(debugName: "torex_count", argNames: ["collection"]);

  @override
  Future<String?> crateApiTorexCurrentPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorexCurrentPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexCurrentPathConstMeta =>
      const TaskConstMeta(debugName: "torex_current_path", argNames: []);

  @override
  Future<void> crateApiTorexDelete({
    required String collection,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexDeleteConstMeta,
        argValues: [collection, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexDeleteConstMeta => const TaskConstMeta(
    debugName: "torex_delete",
    argNames: ["collection", "key"],
  );

  @override
  Future<bool> crateApiTorexExists({
    required String collection,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexExistsConstMeta,
        argValues: [collection, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexExistsConstMeta => const TaskConstMeta(
    debugName: "torex_exists",
    argNames: ["collection", "key"],
  );

  @override
  Future<void> crateApiTorexFlush({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexFlushConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexFlushConstMeta =>
      const TaskConstMeta(debugName: "torex_flush", argNames: ["collection"]);

  @override
  Future<Uint8List?> crateApiTorexGet({
    required String collection,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexGetConstMeta,
        argValues: [collection, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexGetConstMeta => const TaskConstMeta(
    debugName: "torex_get",
    argNames: ["collection", "key"],
  );

  @override
  Future<String?> crateApiTorexGetString({
    required String collection,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexGetStringConstMeta,
        argValues: [collection, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexGetStringConstMeta => const TaskConstMeta(
    debugName: "torex_get_string",
    argNames: ["collection", "key"],
  );

  @override
  Future<void> crateApiTorexInitialize({String? path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexInitializeConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexInitializeConstMeta =>
      const TaskConstMeta(debugName: "torex_initialize", argNames: ["path"]);

  @override
  Future<bool> crateApiTorexIsInitialized() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorexIsInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexIsInitializedConstMeta =>
      const TaskConstMeta(debugName: "torex_is_initialized", argNames: []);

  @override
  Future<List<Uint8List>> crateApiTorexKeys({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexKeysConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexKeysConstMeta =>
      const TaskConstMeta(debugName: "torex_keys", argNames: ["collection"]);

  @override
  Future<List<String>> crateApiTorexListCollections() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexListCollectionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexListCollectionsConstMeta =>
      const TaskConstMeta(debugName: "torex_list_collections", argNames: []);

  @override
  Future<BigInt> crateApiTorexMemtableCount({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexMemtableCountConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexMemtableCountConstMeta => const TaskConstMeta(
    debugName: "torex_memtable_count",
    argNames: ["collection"],
  );

  @override
  Future<void> crateApiTorexOpen({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexOpenConstMeta =>
      const TaskConstMeta(debugName: "torex_open", argNames: ["path"]);

  @override
  Future<void> crateApiTorexPut({
    required String collection,
    required List<int> key,
    required List<int> value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexPutConstMeta,
        argValues: [collection, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexPutConstMeta => const TaskConstMeta(
    debugName: "torex_put",
    argNames: ["collection", "key", "value"],
  );

  @override
  Future<void> crateApiTorexPutString({
    required String collection,
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexPutStringConstMeta,
        argValues: [collection, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexPutStringConstMeta => const TaskConstMeta(
    debugName: "torex_put_string",
    argNames: ["collection", "key", "value"],
  );

  @override
  Future<List<TorexEntry>> crateApiTorexScan({
    required String collection,
    Uint8List? prefix,
    Uint8List? startKey,
    Uint8List? endKey,
    BigInt? limit,
    BigInt? offset,
    required bool reverse,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_opt_list_prim_u_8_strict(prefix, serializer);
          sse_encode_opt_list_prim_u_8_strict(startKey, serializer);
          sse_encode_opt_list_prim_u_8_strict(endKey, serializer);
          sse_encode_opt_box_autoadd_usize(limit, serializer);
          sse_encode_opt_box_autoadd_usize(offset, serializer);
          sse_encode_bool(reverse, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_torex_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexScanConstMeta,
        argValues: [
          collection,
          prefix,
          startKey,
          endKey,
          limit,
          offset,
          reverse,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexScanConstMeta => const TaskConstMeta(
    debugName: "torex_scan",
    argNames: [
      "collection",
      "prefix",
      "startKey",
      "endKey",
      "limit",
      "offset",
      "reverse",
    ],
  );

  @override
  Future<List<(String, String)>> crateApiTorexScanStrings({
    required String collection,
    String? prefix,
    String? startKey,
    String? endKey,
    BigInt? limit,
    BigInt? offset,
    required bool reverse,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_opt_String(prefix, serializer);
          sse_encode_opt_String(startKey, serializer);
          sse_encode_opt_String(endKey, serializer);
          sse_encode_opt_box_autoadd_usize(limit, serializer);
          sse_encode_opt_box_autoadd_usize(offset, serializer);
          sse_encode_bool(reverse, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_string_string,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexScanStringsConstMeta,
        argValues: [
          collection,
          prefix,
          startKey,
          endKey,
          limit,
          offset,
          reverse,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexScanStringsConstMeta => const TaskConstMeta(
    debugName: "torex_scan_strings",
    argNames: [
      "collection",
      "prefix",
      "startKey",
      "endKey",
      "limit",
      "offset",
      "reverse",
    ],
  );

  @override
  Future<BigInt> crateApiTorexSegmentCount({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexSegmentCountConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexSegmentCountConstMeta => const TaskConstMeta(
    debugName: "torex_segment_count",
    argNames: ["collection"],
  );

  @override
  Future<void> crateApiTorexShutdown() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexShutdownConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexShutdownConstMeta =>
      const TaskConstMeta(debugName: "torex_shutdown", argNames: []);

  @override
  Future<String> crateApiTorexVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorexVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexVersionConstMeta =>
      const TaskConstMeta(debugName: "torex_version", argNames: []);

  @override
  Future<BigInt> crateApiTorexWatchCollection({required String collection}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexWatchCollectionConstMeta,
        argValues: [collection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexWatchCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "torex_watch_collection",
        argNames: ["collection"],
      );

  @override
  Future<BigInt> crateApiTorexWatchGlobal() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexWatchGlobalConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexWatchGlobalConstMeta =>
      const TaskConstMeta(debugName: "torex_watch_global", argNames: []);

  @override
  Future<List<TorexWatchEvent>> crateApiTorexWatchPoll({
    required BigInt subscriptionId,
    required int maxEvents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(subscriptionId, serializer);
          sse_encode_u_32(maxEvents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_torex_watch_event,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexWatchPollConstMeta,
        argValues: [subscriptionId, maxEvents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexWatchPollConstMeta => const TaskConstMeta(
    debugName: "torex_watch_poll",
    argNames: ["subscriptionId", "maxEvents"],
  );

  @override
  Future<BigInt> crateApiTorexWatchPrefix({
    required String collection,
    required List<int> prefix,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collection, serializer);
          sse_encode_list_prim_u_8_loose(prefix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexWatchPrefixConstMeta,
        argValues: [collection, prefix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexWatchPrefixConstMeta => const TaskConstMeta(
    debugName: "torex_watch_prefix",
    argNames: ["collection", "prefix"],
  );

  @override
  Future<void> crateApiTorexWatchUnsubscribe({required BigInt subscriptionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(subscriptionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorexWatchUnsubscribeConstMeta,
        argValues: [subscriptionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorexWatchUnsubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "torex_watch_unsubscribe",
        argNames: ["subscriptionId"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(Uint8List, Uint8List)>
  dco_decode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_list_prim_u_8_strict_list_prim_u_8_strict)
        .toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<TorexEntry> dco_decode_list_torex_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torex_entry).toList();
  }

  @protected
  List<TorexWatchEvent> dco_decode_list_torex_watch_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torex_watch_event).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (Uint8List, Uint8List)
  dco_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_prim_u_8_strict(arr[0]),
      dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  TorexEntry dco_decode_torex_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TorexEntry(
      key: dco_decode_list_prim_u_8_strict(arr[0]),
      value: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  TorexWatchEvent dco_decode_torex_watch_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TorexWatchEvent(
      collection: dco_decode_String(arr[0]),
      key: dco_decode_list_prim_u_8_strict(arr[1]),
      changeType: dco_decode_u_8(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(Uint8List, Uint8List)>
  sse_decode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(Uint8List, Uint8List)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorexEntry> sse_decode_list_torex_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorexEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torex_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorexWatchEvent> sse_decode_list_torex_watch_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorexWatchEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torex_watch_event(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (Uint8List, Uint8List)
  sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_field1 = sse_decode_list_prim_u_8_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  TorexEntry sse_decode_torex_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_list_prim_u_8_strict(deserializer);
    var var_value = sse_decode_list_prim_u_8_strict(deserializer);
    return TorexEntry(key: var_key, value: var_value);
  }

  @protected
  TorexWatchEvent sse_decode_torex_watch_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_collection = sse_decode_String(deserializer);
    var var_key = sse_decode_list_prim_u_8_strict(deserializer);
    var var_changeType = sse_decode_u_8(deserializer);
    return TorexWatchEvent(
      collection: var_collection,
      key: var_key,
      changeType: var_changeType,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    List<(Uint8List, Uint8List)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_list_prim_u_8_strict_list_prim_u_8_strict(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torex_entry(
    List<TorexEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torex_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torex_watch_event(
    List<TorexWatchEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torex_watch_event(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    (Uint8List, Uint8List) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.$1, serializer);
    sse_encode_list_prim_u_8_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_torex_entry(TorexEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.key, serializer);
    sse_encode_list_prim_u_8_strict(self.value, serializer);
  }

  @protected
  void sse_encode_torex_watch_event(
    TorexWatchEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.collection, serializer);
    sse_encode_list_prim_u_8_strict(self.key, serializer);
    sse_encode_u_8(self.changeType, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
